// Shamelessly stole this code from Troy Zhang (https://github.com/ivylongbow/AoC-2022-Csharp/blob/main/README.md-Updater/Program.cs)
// and adapted the parsing to match my project naming conventions

// Parsing the solution file for Projects with Name that starts with "Day_[n]_" where [n] is a number indicating the xth day.
using System.Text.RegularExpressions;

string[] solution = File.ReadAllLines("../../../../AdventOfCode2022.sln");

int MaxLength = 20;  // this will be the number of qualified Projects found, which means number of days completed.

List<string> Days = new();

foreach (string s in solution)
{
    if (s.StartsWith("Project("))
    {
        Match m = Regex.Match(s, @"Day\d\d");   // grab project names that start with "Day" followed by 2-digit number
        
        if (m.Success)
        {
            string dayNum = m.Groups[0].Value;  //.Substring(3, 2);

            Days.Add(dayNum);
            if (MaxLength < dayNum.Length)
                MaxLength = dayNum.Length;
        }

        //string project = s.Split('=', StringSplitOptions.TrimEntries)[1].Split(',')[0];
        //string[] StoryName = project[1..(project.Length - 1)].Split('_');
        //if (StoryName.Length > 2)
        //{
        //    if (StoryName[0] == "Day" && StoryName[2].Length > 0)
        //    {
        //        Days.Add(string.Join('_', StoryName[1..]));
        //        if (MaxLength < project.Length)
        //            MaxLength = project.Length;
        //    }
        //}
    }
    else if (s.StartsWith("Global"))    // end the Parsing process.
        break;
}

// Formatting the output string for file "Readme.md"
int DayProgress = Days.Count;
List<string> ReadMe = new()
            {
                "# Advent of Code 2022 in C#",
                "- This fancy readme style is inspired by [Marcus Shu](https://github.com/shulkx/advent-of-code/tree/main/adventofcode2022).",
                "- This README.md file is generated by program by [Troy Zhang](https://github.com/ivylongbow/AoC-2022-Csharp).",
                "- The source code can be found [here](https://github.com/ivylongbow/AoC-2022-Csharp/blob/main/README.md-Updater/Program.cs).",
                "",
                $"## Progression and Navigation    ![Progress](https://progress-bar.dev/{DayProgress}/?scale=25&title=Days&width=240&suffix=/25)",
                "",
                "| DAY                                                          | STARS | C#                            | Solution Description |",
                "| ------------------------------------------------------------ | ----- | ----------------------------- | -------------------- |"
            };

for (int i = 1; i <= DayProgress; i++)   // starting from day 7, I got lazy, the main source code file naming convension changed to "./Day_[n]/Day_[n].cs"
{
    //string[] StoryName = Days[i - 1].Split('_');
    ReadMe.Add($"| [Day {Days[i - 1].Substring(3, 2)}: {string.Join(' ', "day title")}](https://adventofcode.com/2022/day/{i}){new string(' ', MaxLength - Days[i - 1].Length)}| ⭐️⭐️ | [Solution](./Day{i.ToString("00")}/Program.cs){new string(' ', MaxLength - i.ToString().Length)}|                      |");
}

for (int i = DayProgress + 1; i <= 25; i++)  // placeholders for upcoming days
    ReadMe.Add($"| [Day {i}](https://adventofcode.com/2022/day/{i})              |       |                               |                      |");



foreach (string s in ReadMe)
    Console.WriteLine(s);
//File.WriteAllLines("../../../../README.md", ReadMe);